name: First Workflow
on: workflow_dispatch
jobs:
  fist-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing greetings
        run: echo "Hola crvrgs"
      - name: Print goodbye
        run: echo "Nos vemos pdjo"
